version: '3'

tasks:
  default:
    desc: List tasks
    cmd: task --list

  setup:
    desc: Install dependencies for backend and frontend
    cmds:
      - cmd: cd backend && uv sync
      - cmd: cd frontend && npm install

  dev:
    desc: Run the full stack (Backend + Frontend)
    deps: [kill]
    cmds:
      - task: dev:up

  dev:up:
    desc: internal task to run services
    deps: [dev:backend, dev:frontend]

  dev:backend:
    desc: Run backend API (port 8000)
    dir: backend
    cmd: uv run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  dev:frontend:
    desc: Run frontend (port 5173)
    dir: frontend
    cmd: npm run dev -- --host

  kill:
    desc: Kill processes on ports 8000 and 5173
    cmds:
      - fuser -k 8000/tcp 5173/tcp 5174/tcp || true
    silent: true

  db:init:
    desc: "Show SQL to initialize database (Run in Supabase Dashboard)"
    cmd: cat backend/init_db.sql

  lint:
    desc: Lint and format code
    cmds:
      - cd backend && uv run ruff check --fix .
      - cd backend && uv run ruff format .
      - cd frontend && npx prettier --write .
      - cd frontend && ESLINT_USE_FLAT_CONFIG=false npx eslint . --ext .js,.jsx --fix