version: "3"

tasks:
  default:
    desc: タスク一覧を表示
    cmd: task --list

  setup:
    desc: "依存インストール (backend: uv sync, frontend: npm install)"
    cmds:
      - cmd: cd backend && uv sync
      - cmd: cd frontend && npm install

  dev:
    desc: バックエンドとフロントエンドを同時起動
    deps: [dev:backend, dev:frontend]

  dev:backend:
    desc: FastAPI 開発サーバー (http://localhost:8000)
    dir: backend
    cmd: uv run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  dev:frontend:
    desc: Vite 開発サーバー (http://localhost:5173)
    dir: frontend
    cmd: npm run dev -- --host

  db:init:
    desc: DB初期化SQLを表示
    cmd: cat backend/init_db.sql

  lint:
    desc: Lint / format (backend Ruff, frontend Prettier+ESLint)
    cmds:
      - cmd: cd backend && uv run ruff check --fix .
      - cmd: cd backend && uv run ruff format .
      - cmd: cd frontend && npm run format
      - cmd: cd frontend && npm run lint:fix
