version: "3"

tasks:
  default:
    desc: タスク一覧を表示
    cmd: task --list

  setup:
    desc: "依存インストール (backend: uv sync, frontend: npm install)"
    cmds:
      - task: setup:backend
      - task: setup:frontend

  setup:backend:
    cmd: uv sync

  setup:frontend:
    dir: frontend
    cmd: npm install

  dev:
    desc: バックエンドとフロントエンドを同時起動
    deps: [dev:backend, dev:frontend]

  dev:backend:
    desc: FastAPI 開発サーバー (http://localhost:8000)
    cmd: uv run uvicorn api.app.main:app --reload --host 0.0.0.0 --port 8000

  dev:frontend:
    desc: Vite 開発サーバー (http://localhost:5173)
    dir: frontend
    cmd: npm run dev -- --host

  build:
    desc: フロントエンドのビルド
    dir: frontend
    cmd: npm run build

  preview:
    desc: フロントエンドのプレビュー (ビルド後)
    dir: frontend
    cmd: npm run preview

  lint:
    desc: Lint / format (backend Ruff, frontend Prettier+ESLint)
    cmds:
      - task: lint:backend
      - task: lint:frontend

  lint:backend:
    cmds:
      - uv run ruff check --fix api/app
      - uv run ruff format api/app

  lint:frontend:
    dir: frontend
    cmds:
      - npm run format
      - npm run lint:fix

  db:init:
    desc: DB初期化用SQLを表示
    cmd: cat backend/init_db.sql

  clean:
    desc: キャッシュとビルドアーティファクトの削除
    ignore_error: true
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - rm -rf backend/.ruff_cache
      - rm -rf frontend/dist

  kill:
    desc: 開発サーバーのポート(8000, 5173)を強制解放
    ignore_error: true
    cmds:
      - fuser -k 8000/tcp
      - fuser -k 5173/tcp

  issues:
    desc: GitHub Issue一覧を表示 (開発ループの起点)
    cmd: gh issue list --limit 20

  issues:critical:
    desc: 重要なIssueを表示 (開発ループの優先順位)
    cmd: gh issue list --label "critical" --limit 10 || gh issue list --limit 5
