version: "3.9"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: .
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports: ["8000:8000"]
    depends_on: [qdrant, redis]
    volumes:
      - ./rsg.db:/app/rsg.db
    command: sh -c "touch rsg.db && uvicorn rsg.api:app --host 0.0.0.0 --port 8000"

  worker:
    build: .
    command: python worker.py
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on: [qdrant, redis]
    volumes:
      - ./rsg.db:/app/rsg.db

  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports: ["6333:6333"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
